[tool.poetry]
name = "phoenix-transcriber"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "phoenix_transcriber", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
python-socketio = "^5.11.2"
jinja2 = "^3.1.4"
python-multipart = "^0.0.9"
faster-whisper = "^1.0.3"
torch = "^2.3.0"
sqlalchemy = "^2.0.30"
aiofiles = "^23.2.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
